### ISSUE TITLE
IDE - Remove current text in editor on reopen file dialog

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/greenBerry#10]

**Comment by Abdur-rahmaanJ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [greenBerry](https://trello.com/c/iZouVJVW/3-greenberry)

**Comment by Abdur-rahmaanJ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [greenBerry](https://trello.com/c/iZouVJVW/3-greenberry)

**Comment by TimThuma** [comment]
Pull requested a fix
