### ISSUE TITLE
substitute py's eval for a complete postfix evaluater

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/greenBerry#13]

**Comment by KushalVijay** [comment]
I have gone through the documentation and Since i am a beginner, i did not understood in which file i have to make changes i.e. write code for " postfix evaluation".
Please help

**Comment by Abdur-rahmaanJ** [comment]
well if i give you

2+3-5*7

can you write a python program to evaluate it? if you can, i'll guide you where to insert it!

**Comment by Abdur-rahmaanJ** [comment]
in python. when you code it, i'll tell you where to put 👌

**Comment by KushalVijay** [comment]
Yes,I have written the code and its running properly .
Now please guide me where to put it,then i will send you a pull request.

**Comment by KushalVijay** [comment]
But postfix to infix evaluation is only valid for expression having digits between 0 to 9. For higher numbers the original expression should have separator like space between all elements (operators and operands) of given expression.

**Comment by Abdur-rahmaanJ** [comment]
nooo solve this as that's what is meant by evaluating 1+2-5*8/4

**Comment by KushalVijay** [comment]
Yes Sir, my code can solve this expression easily .Let me pull a request ,then you can review it if there is any issue then let me know .
Is it ok?

**Comment by Abdur-rahmaanJ** [comment]
ok fine, you can put a utils file and then put it in a function

**Comment by KushalVijay** [comment]
Sorry ,for the late response.Please review the pull request .
For the example above you have given me ,there is an ambiguity ,for correct answer, the expression should be like 
1+2-(5*8)/4=-7 
Thankyou
