### ISSUE TITLE
keyword errors in statements

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/greenberry#2]
## keywords unusable in print statement

`print make`

returns error

**Comment by ajjayymahato** [comment]
Is this issue still open? I would like to take up this issue can you please assign this to me?

**Comment by Abdur-rahmaanJ** [comment]
@ajjayymahato Yes

**Comment by ajjayymahato** [comment]
Is this open for Hacktoberfest?

**Comment by Abdur-rahmaanJ** [comment]
@ajjayymahato Yes!

**Comment by ajjayymahato** [comment]
Can you please elaborate on this issue?

**Comment by Abdur-rahmaanJ** [comment]
@ajjayymahato You tried print make?

**Comment by ajjayymahato** [comment]
working on it

**Comment by ajjayymahato** [comment]
Inside my file.gb I put the following code : 
**_class Man:power = 10 action walk: print walking...
make Man walk_**

In the terminal i executed **greenberry file.gb**
This returned me the output as _walking..._

Can I know what exactly is the issue?

**Comment by ajjayymahato** [comment]
What is expected output from **print make**?

**Comment by Abdur-rahmaanJ** [comment]
`make`

**Comment by 4the4ryushin** [comment]
can i work on this issue too?

**Comment by Abdur-rahmaanJ** [comment]
@4the4ryushin Ok!

**Comment by 4the4ryushin** [comment]
there's really big issue with gb.py file , it imports S for symbols and but S class doesn't contain error messages and each except section is trying  to access error messages from S class but errors are in E class which not even imported
working on it ,  shall i open a new issue  for this? or fix it along with this issue? because before fixing the error messaged issue working  print make is impossible

**Comment by 4the4ryushin** [comment]
okay found the fix for print make but its with every keyword followed by print 
eg: print if would make the same error isn't it better for string printing we should  implement the use of quotes  (",' ) like other programming language

**Comment by 4the4ryushin** [comment]
i am fixing the error class and make issue but for rest i would suggest you should open a new issue

**Comment by 4the4ryushin** [comment]
okay there are more issues with function calls and if statements i am fixing them all under single PR

**Comment by 4the4ryushin** [comment]
i have made the PR lemme know

**Comment by 4the4ryushin** [comment]
i guess i have fixed all the working keyword with print in the previous PR ,
