### ISSUE TITLE
update grammar.txt

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/greenBerry#31]

**Comment by verascity** [comment]
Hello! Update how? What parts need updating?

**Comment by Abdur-rahmaanJ** [comment]
@verascity actually see the actual grammar [here](https://abdur-rahmaanj.github.io/greenBerry/syntax.html) and see grammar.txt, include all

if you want to change grammar notation completely, feel free

**Comment by Abdur-rahmaanJ** [comment]
completed :+1:
