### ISSUE TITLE
Logo Should be in all pages

### ISSUE THREAD

**Issue by Dev49199** [Abdur-rahmaanJ/greenBerry#36]

**Comment by Abdur-rahmaanJ** [comment]
hum very important

**Comment by Abdur-rahmaanJ** [comment]
just add logo below nav bar

**Comment by Dev49199** [comment]
Okkk thanks

**Comment by Abdur-rahmaanJ** [comment]
just change place ^^_

**Comment by Abdur-rahmaanJ** [comment]
@Dev49199 a PR alrrady catered for it, just propose some fine tuning or whatever you wish ^^
