### ISSUE TITLE
add a comprehensive capture print in greenberry/utils.py

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/greenberry#46]
currently [here](https://github.com/Abdur-rahmaanJ/greenBerry/blob/master/greenberry/utils.py), we are having two capture_print functions, write a function that handles functions with parameters (including many args as well as optional args) and no parameters. hint: might use flags / optional args

**Comment by hassaanseeker** [comment]
I would like to work on this can you tell me a bit more.
