### ISSUE TITLE
make maths_eval support brackets

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/greenBerry#48]
see maths_eval [here](https://github.com/Abdur-rahmaanJ/greenBerry/blob/master/greenberry/utils.py). add brackets support to it so that expressions as (1+2)+3 can be evaluated

**Comment by Aarthi-V** [comment]
Hi,
I am new to open source. I was looking for projects to contribute to and that's when I came across greenBerry.
Could you elaborate on this issue? 
Doesn't maths_eval already support brackets?
Please help me understand this issue

Thanks
Aarthi

**Comment by Aarthi-V** [comment]
Thanks for the update.
Will look at the other issues

**Comment by jlim2** [comment]
Hi @Abdur-rahmaanJ  and @TimThuma, I am also new to open-source. greenBerry seems to be a cool project and I would like to contribute! Is this issue still up-for-grab? If so, I would like to look into it!

**Comment by TimThuma** [comment]
Yes, all issues that are currently open still need to be solved and aren't picked by anyone yet. Your help would be greatly appreciated.

**Comment by jlim2** [comment]
Sorry I have not been able to complete the task yet. Fixed maths_eval (now named infix_eval) to take care of brackets and made more utils test. However, there is a bug when the user enters 2+ digit numbers. I am going to work on it as soon as I am done with finals!

**Comment by TimThuma** [comment]
No problem, take your time. Nobody is forcing you to hurry.
It's great to hear that you've already done most of the work. I'll be waiting for when you're finished.

**Comment by Abdur-rahmaanJ** [comment]
@Aarthi-V mail me on arj.python@gmail.com, i'll guide you through some aspects of the projects!. sorry for delay

**Comment by Abdur-rahmaanJ** [comment]
@jlim2  sent mail, please check!

**Comment by rajeshshanmuga** [comment]
Hi, 
I'm new to contributing. maths_eval is already supporting brackets. If that is not the issue, can you please elobrate it more about the issue.

**Comment by Abdur-rahmaanJ** [comment]
@rajeshshanmuga we need docs more. Yes the issue is solved. I mean technical documentations.
