### ISSUE TITLE
Add search function to IDE

### ISSUE THREAD

**Issue by TimThuma** [Abdur-rahmaanJ/greenBerry#54]
Make a new option on the menu that would trigger a search function. When clicked it would pop-up a small box in which user can type input. Then find this input in the text and highlight it.
Then you can carry out a replace function from this.

**Comment by avidnomads** [comment]
@Abdur-rahmaanJ @TimThuma 
Still interested in this? I plan to work on it later today.

**Comment by TimThuma** [comment]
@avidnomads that would be great! What I want here is basically like a search function in any other ide.

**Comment by Abdur-rahmaanJ** [comment]
you have my blessings ^^_
