### ISSUE TITLE
add ide usage tutorial

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/greenBerry#58]
either on wiki or a separate markdown document. add code running instructions on ide with screenshots

**Comment by 5aumy4** [comment]
hello, i am new to contributing to open source orgs, can I take this issue?

**Comment by Abdur-rahmaanJ** [comment]
ok!

**Comment by 5aumy4** [comment]
But the download button in https://www.appinv.science/greenBerry/ is leading me to https://github.com/Abdur-rahmaanJ/greenBerry;
how should the code be downloaded?
since i will be able to make a tutorial only if I am familiar with it's usage

**Comment by 5aumy4** [comment]
i tried the instructions, and this is where I ended
can you please tell me how can i load a .gb file here?

![greenBerryinst](https://user-images.githubusercontent.com/67415005/86444247-19f73c80-bd2e-11ea-8802-eedfb4b1af9d.png)

**Comment by TimThuma** [comment]
You should run "python gb_ide.py" from your command line. In your screenshot you first ran "python gb_repl.py", which is not the correct way. Once gb_ide.py is opened, you will see a window which you can use as an IDE.
![image](https://user-images.githubusercontent.com/30806431/86467548-dacce980-bd35-11ea-87d9-40ecca051263.png)

**Comment by 5aumy4** [comment]
Got it!
I tried some code too, and it ran nicely
what command am i supposed to run after this?
and also, i ran 'python gb_ide.py' after this and I cannot make out what the output here means..
![gb_main running](https://user-images.githubusercontent.com/67415005/86472149-5346a100-bd5c-11ea-8d69-2293bea0cfa1.png)

**Comment by TimThuma** [comment]
In this screenshot you ran gb_main.py instead of gb_ide.py
Once you run **gb_ide.py**, there will be no output in command line, only the IDE window will pop up.

**Comment by 5aumy4** [comment]
yes i did that, and it worked pretty well

**Comment by 5aumy4** [comment]
i was just asking that what is the use of 'python gb_main.py' command

**Comment by TimThuma** [comment]
Oh, it just runs whatever is inside main.gb

**Comment by 5aumy4** [comment]
Alright!
I will come up with the tutorial in about 3 days
Will that be fine?

**Comment by TimThuma** [comment]
Yes sure, take your time.

**Comment by TimThuma** [comment]
Resolved with pull request #73
