### ISSUE TITLE
Little thought about plotting.

### ISSUE THREAD

**Issue by madcpt** [Abdur-rahmaanJ/greenBerry#59]
In the syntax documentation, the command 
~~~
plot 1-2-3-4-5 time[s], 24-34-56-78-45 speed[m/s]
~~~
 plots a curve, and how about expands the command to 
~~~
plot 'x.txt' time[s], 'y.txt' speed[m/s]
~~~
, where x-axis and y-axis data are all stored in the 'x.txt' and 'y.txt'?
Of course this is just part of the possible expansion, I believe I can make the plotting command better.

**Comment by Abdur-rahmaanJ** [comment]
yes, we can extend the command 👍

**Comment by MattyHsu** [comment]
Actually I am a starter in open source, maybe I should implement this thought and try to pull request?

**Comment by Abdur-rahmaanJ** [comment]
Yes, any question or anything you don't understand, just ask!

**Comment by MattyHsu** [comment]
thnxx, I'll see what I can do.
