### ISSUE TITLE
Support for multi-line print statements

### ISSUE THREAD

**Issue by Aarthi-V** [Abdur-rahmaanJ/greenBerry#61]
I tried the following code snippet in the IDE:
`print string good going`
`Toby`
Expected Output:
`good going`
`Toby`
And the actual output was just:
`good going`

I believe it would be better if there was an error message displayed in such cases. Additionally we can also add code to support multi-line print statements.

Please let me know what you think.

**Comment by Abdur-rahmaanJ** [comment]
@Aarthi-V by design is a one-line statement language and as such does not support multi-line
