### ISSUE TITLE
group utilities files in folder

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/greenBerry#64]
create a folder named gb_utils and add the following files to it
```
greenberry_print
greenberry_lex
greenberry_parse
greenberry_plot
greenberry_search
greenberry_var_type
```

fix imports in greenBerry.py after

**Comment by phamt2** [comment]
I would like to help with this issue but I'm not entirely sure on how to fix the imports in the greenBerry.py afterwards

**Comment by Abdur-rahmaanJ** [comment]
@phamt2 just add an init.py in utils folder then from utils.greenberry_print import ...

**Comment by realnaveen** [comment]
Hi, can I work on this, if no one is?

**Comment by anirudnits** [comment]
Is anybody currently assigned to this? Otherwise I want to work on this.
