### ISSUE TITLE
Support for >= and <= on if conditionals

### ISSUE THREAD

**Issue by chrigkou** [Abdur-rahmaanJ/greenBerry#70]
I was going through the GreenBerry code and syntax and noticed that 'greater than or equal' ( >= ) and 'less than or equal' ( <= ) signs are currently not supported for if conditionals. I would like to work on it and add this functionality if that's alright.

**Comment by Abdur-rahmaanJ** [comment]
@chrigkou ok that's fine!

**Comment by chrigkou** [comment]
I make a pull request for the issue! Adjusted greenberry_search/search_symbol to look for operators consisting of more than one symbol as well.
