### ISSUE TITLE
ADD MORE SYMBOL KEYWORDS

### ISSUE THREAD

**Issue by fms12** [Abdur-rahmaanJ/greenberry#77]
LIKE:-

- ELIF
- RETURN
- POWER
- FLOAT
- ABSOLUTE VALUE
- MIN
- MAX
- LENGTH

**Comment by fms12** [comment]
CAN I START WORKING ON IT ?

**Comment by Abdur-rahmaanJ** [comment]
@fms12 yes, sure!

**Comment by 4the4ryushin** [comment]
> CAN I START WORKING ON IT ?
 hey are you still working on it?
